services:
  - type: worker
    name: youtube-comment-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 main.py"
    envVars:
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: CHANNEL_ID
        sync: false
